<?php
/**
 * Created by PhpStorm.
 * User: jomiao
 * Date: 2018/3/7
 * Time: 下午3:38
 */

namespace mock\controller;

use spaphp\http\Controller as BaseController;

abstract class Controller extends BaseController
{

    protected function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        header("content-type:application/json;");
        header("Access-Control-Allow-Origin: *");
        header("Access-Control-Allow-Methods: GET, POST, DELETE, PUT, PATCH, OPTIONS");
        header("Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept");
    }
}
